// React and CSS.

import React, { useEffect, useState, useRef } from "react";
import './App.css';
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader

// Componenets.

import Mint from "./components/Mint";
import Navbar from "./components/navbar/navbar";
import { Carousel } from 'react-responsive-carousel';
import Rellax from 'rellax';
// Resources.

import pixelcowboy from '../src/assets/images/pixelCowboy1.png';
import discord from '../src/assets/images/discord.png';
import twitter from '../src/assets/images/twitter.png';
import medium from '../src/assets/images/medium.png';

import cowboy1 from '../src/assets/images/cowboy1.png';
import cowboy2 from '../src/assets/images/cowboy2.png';
import cowboy3 from '../src/assets/images/cowboy3.png';
import cowboy4 from '../src/assets/images/cowboy4.png';
import cowboy5 from '../src/assets/images/cowboy5.png';

// Remove later..

const showAlert = () => {

  if (window.confirm("Minting will be announced later on. In the mean time, join us at the saloon!🤠")) 
  {
    window.location.href='https://discord.gg/PfWgPDnq7F';
  };

}

class App extends React.Component {

  componentDidMount(){
		this.rellax = new Rellax('.rellax',
			
		);
	}


// <a  id="header_btn" href="/minting">  </a>  
  
// Insert route for mint later.
render (){
  return (

    <div className="App">
	
    <section class="section section-top">
    <Navbar/>
     <div class="content rellax" data-rellax-speed="4">
   
       <h1 id="header_title">Pixel Cowboy's 7.000 NFT Collection.</h1>
      
          <button type="button" id="header_btn" class="btn btn-primary" onClick={showAlert} 
            class="btn btn-primary">Mint NFT
            </button>
         
       <div> 
</div>

     </div>
   </section>

   <section class="section section-stream">

     <div class="image-container">
     <img
       class="rellax"
       src={discord} 
       alt="Loading.."
       data-rellax-speed="-4" data-rellax-xs-speed="-3"
     />
       <img
       class="rellax"
       src={twitter} 
       alt="Loading.."
       data-rellax-speed="-2.5" data-rellax-xs-speed="-3"
     />
       <img
       class="rellax"
       src={medium} 
       alt="Loading.."
       data-rellax-speed="0" data-rellax-xs-speed="-3"
     />
     </div>		
   </section>
     
   <section class="section section-grid">

     
     
     <div class="rellax" data-rellax-speed="1" data-rellax-xs-speed="3">
       <i class="fas fa-video fa-3x secondary-text"></i>
       <h2>Discord<span class="secondary-text dot">.</span></h2>
       <p>
         Join our Discord server and hang out with other cowboys in the saloon!🤠
       </p>
       <a  href="https://discord.gg/PfWgPDnq7F" class="btn btn-primary">Join Discord</a>
     </div>
     <div class="rellax" data-rellax-speed="4" data-rellax-xs-speed="3">
       <i class="fas fa-users fa-3x secondary-text"></i>
       <h2>Twitter<span class="secondary-text dot">.</span></h2>
       <p>
         Follow us on Twitter to get fast updates and news about the Pixel Cowboys.🤠
       </p>
       <a  href="https://twitter.com/PixelCowboys" class="btn btn-primary">Follow Twitter</a>
     </div>
     <div class="rellax" data-rellax-speed="7" data-rellax-xs-speed="3">
       <i class="fas fa-book fa-3x secondary-text"></i>
       <h2>Medium<span class="secondary-text dot">.</span></h2>
       <p>
         Stay up to date by reading our blog over at Medium.🤠 
       </p>
       <a  href="https://dynamic-network.medium.com/" class="btn btn-primary">Read Medium</a>
     </div>
   </section>

 <div class="section-container">

 <div class="about-header">
   
<div class="content rellax" data-rellax-speed="2">
     <h1>About the Cowboys</h1>
     </div>
     </div>

   <section class="section section-stream2">
     <img id="pixelcowboy"
       class="play rellax"
       src={pixelcowboy} 
       alt="Loading.."
       data-rellax-speed="1" data-rellax-xs-speed="-5"
     />
  
  <div class="content rellax" data-rellax-speed="1.2">
    <div>
      <h2 class="secondary-text">Limited Collection</h2>
      <p id="about-p">
        Only 7000 Pixel Cowboys will ever be minted. Each cowboy will be unique and randomly 
        generated by code. 
      </p>
    </div>
    <div>
      <h2 class="secondary-text">Fair Minting</h2>
      <p id="about-p">
      The minting will be open to the public and we have decided on a fair minting price of (TBA).
        This is because the community is what's important, not the revenue from the minting. 
      </p>
    </div>
  <div>
      <h2 class="secondary-text">Community Driven</h2>
      <p id="about-p">
        The cowboys have each others back. We believe that the Pixel Cowboy 
        community knows whats best for the future of the cowboys.
      </p>
    </div>
  <div>
      <h2 class="secondary-text">Owner Rewards</h2>
      <p id="about-p">
        Pixel Cowboys will be doing giveaways for all cowboy holders with the opportunity to win exclusive rewards.
      </p>
    </div>
  </div>

</section>
</div>
  


<div class="section-container"> 

<div class="content rellax" data-rellax-speed="2">

  
<div class="roadmap-header">
     <h1>Road_Map</h1>
     </div>
     </div>


<section class="section section-grid2">


<div class="content rellax" data-rellax-speed="-1">
    <div class="section-grid2-item">
     <h2>Build the Community </h2>
     <p>Reach 500 cowboys in Discord.✅</p> 
     <br/>
     <p>Reach 500 followers on Twitter.🚧</p> 
     <br/>
     <p>Fill 100 spots on the whitelist.🚧</p> 
    </div>
 </div>
<div class="content rellax" data-rellax-speed="-0.75">
    <div class="section-grid2-item">
     <h2>Launch Website</h2>
     <p>Get the website up and running.✅</p> 
     <br/>
     <p>Update road map, team and other components.🚧</p> 
     <br/>
     <p>Add minor changes to the site for a better user experience.</p> 
    </div>
 </div>

 <div class="content rellax" data-rellax-speed="-0.5">

    <div class="section-grid2-item">

     <h2> Grow the Community</h2>

     <p>Reach 1000+ cowboys in Discord.🚧</p> 
      <br/>
      <p>Reach 1000+ followers on Twitter.</p> 
      <br/>
      <p>Fill round two of whitelist spots.</p> 
      <br/>
    </div>

 </div>


 <div class="content rellax" data-rellax-speed="-1">
  <div class="mobile-spacing">
    <div class="section-grid2-item">
   
     <h2>Start Giveaways</h2>

     <p> More Details Coming Soon!</p> 

    </div>
</div>
 </div>



 <div class="content rellax" data-rellax-speed="-0.75">

    <div class="section-grid2-item">

     <h2>Finish the last Designs</h2>

     <p> More Details Coming Soon!</p> 

    </div>

 </div>



 <div class="content rellax" data-rellax-speed="-0.5">

    <div class="section-grid2-item">

     <h2 id="pixel-launch">Launch of the Pixel Cowboys!</h2>

     <p> More Details Coming Soon!</p>  

    </div>

 </div>

 

</section>

</div>


<div class="carousel-section">
        <Carousel showArrows={true} emulateTouch={true} thumbWidth={80}  >
                <div>
                    <img id="carousel-img" src={cowboy1} />
                    <p id="legend">Space Commander Cowboy</p>
                </div>
                <div>
                    <img id="carousel-img"  src={cowboy2}  />
                    <p id="legend">Zombie Pirate Cowboy</p>
                </div>
                <div>
                    <img id="carousel-img"  src={cowboy5}  />
                    <p id="legend">Light Saber Cowboy</p>
                </div>
                <div>
                    <img id="carousel-img"  src={cowboy3}  />
                    <p id="legend">Red Eyed Cowboy</p>
                </div>
                <div>
                    <img id="carousel-img"  src={cowboy4}  />
                    <p id="legend">Indian Fighter Cowboy</p>
                </div>
            </Carousel>
</div>

<div class="section-container"> 


<section class="section section-team">
 </section>
 <section class="section section-team">
 </section>


 <div class="content rellax" data-rellax-speed="2">

 <div class="team-header">

   <h1>Sheriffs</h1>

 </div>
</div>
 <section class="section section-team">

 <div class="content rellax" data-rellax-speed="1.75">

   <div class="team-item">

     <img src={pixelcowboy} alt="Loading.."/>

       <h2>Clint Eastwood</h2>

        <p>This sheriff is out in the desert right now and will be back soon.</p>  
   </div>
 </div>

 <div class="content rellax" data-rellax-speed="1.5">

   <div class="team-item">

     <img src={pixelcowboy} alt="Loading.."/>

       <h2>Belle Starr</h2>

         <p> This sheriff is out in the desert right now and will be back soon. 
         </p> 
     </div>
   </div>
 <div class="content rellax" data-rellax-speed="1.25">

     <div class="team-item">

     <img src={pixelcowboy} alt="Loading.."/>

       <h2>Wyatt Earp</h2>

         <p> This sheriff is out in the desert right now and will be back soon.
         </p> 
   </div>

 </div>
 
 <div class="content rellax" data-rellax-speed="1">

   <div class="team-item">

     <img src={pixelcowboy} alt="Loading.."/>

       <h2>Billy The Kid</h2>

         <p> This sheriff is out in the desert right now and will be back soon.
         </p> 
     </div>
 </div>
 <div class="content rellax" data-rellax-speed="0.75">

<div class="team-item">

  <img src={pixelcowboy} alt="Loading.."/>

    <h2>Harmonica</h2>

      <p> This sheriff is out in the dessert right now and will be back soon.
      </p> 
  </div>
</div>
  

 </section>
   

</div>

   <footer class="footer">
     <ul>
       <li><a href="#">Faq</a></li>
       <li><a href="#">Terms of Use</a></li>
       <li><a href="#">Privacy Notice</a></li>
       <li><a href="#">Contact Us</a></li>
       <li><a href="#">About Us</a></li>
     </ul>
   </footer>
   </div>
     
  );
}
}

export default App;



